name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # 毎日更新
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download stats image
        run: |
          curl -L "https://github-readme-stats-g1f76q19t-mikito5s-projects.vercel.app/api?username=mikito5&show_icons=true&theme=radical&format=png" \
          -o stats.png

      - name: Commit image
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add stats.png
          git commit -m "Update GitHub stats" || exit 0
          git push
